baseURL = "https://wearewaylandnow.com/"
languageCode = "en-us"
title = "We are Wayland now!"

enableRobotsTXT = true

assetDir = "src"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[build]
  noJSConfigInAssets = true
